In [1]:
import os
import json
import h5py
import numpy as np

import robomimic
import robomimic.utils.file_utils as FileUtils
import robomimic.utils.env_utils as EnvUtils
import robomimic.utils.obs_utils as ObsUtils
import imageio
import tqdm
from robomimic.utils.file_utils import create_hdf5_filter_key
import shutil

ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /home/ns1254/mimicgen/envs/robomimic/robomimic/scripts/setup_macros.py
)


In [2]:
# dataset_path = "/home/ns1254/gib/dataset/lift_ph_low200.hdf5"
# dataset_path = "/home/ns1254/dataset_mimicgen/square134_2_0ind_abs.hdf5" 
dataset_path = "/home/ns1254/data_franka/drawer/mixed_o40z5tal3l5taz5.hdf5"

f = h5py.File(dataset_path, "r+")
demos = list(f["data"].keys())

In [3]:
lengths=[]
for demo_name in demos:
    demo=f['data'][demo_name]
    num_samples=demo.attrs['num_samples']
    lengths.append(num_samples)

lengths=np.array(lengths)

print('Number of demos: ', len(demos))
print('Max length: ', np.max(lengths))
print('Min length: ', np.min(lengths))
print('Mean length: ', np.mean(lengths))

Number of demos:  58
Max length:  1200
Min length:  224
Mean length:  496.17241379310343


In [4]:
for key in f['mask'].keys():
    print(key, f['mask'][key])

KeyError: "Unable to synchronously open object (object 'mask' doesn't exist)"

In [5]:
demo_name = demos[0]
demo=f['data'][demo_name]
num_samples=demo.attrs['num_samples']

demo_name, num_samples,  demo['obs'].keys(), demo.keys()

('demo_0',
 283,
 <KeysViewHDF5 ['agentview_rgb', 'ee_states', 'eye_in_hand_rgb', 'gripper_states', 'joint_states']>,
 <KeysViewHDF5 ['actions', 'obs']>)

In [6]:
for demo_name in demos: 
    num_samples=f['data'][demo_name].attrs['num_samples']
    break 

In [7]:
demo_name="demo_24"

In [8]:
demo_no=np.ones(num_samples)*int(demo_name.split("_")[1])
demo_indices = np.arange(num_samples)
demo_indices

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [9]:
for demo_name in demos: 
    num_samples=f['data'][demo_name].attrs['num_samples']
    # demo_info = [f"{demo_name}_{i}" for i in range(num_samples)]
    # f["data"][demo_name].create_dataset(f'obs/uid', data=demo_info)
    demo_nos=np.ones(num_samples)*int(demo_name.split("_")[1])
    demo_indices = np.arange(num_samples)

    f["data"][demo_name].create_dataset(f'obs/demo_no', data=demo_nos)
    f["data"][demo_name].create_dataset(f'obs/index_in_demo', data=demo_indices)

In [10]:
len(demos)

58

In [11]:
demo_name = demos[0]
demo=f['data'][demo_name]
num_samples=demo.attrs['num_samples']

demo_name, num_samples,  demo['obs'].keys(), demo.keys()

('demo_0',
 283,
 <KeysViewHDF5 ['agentview_rgb', 'demo_no', 'ee_states', 'eye_in_hand_rgb', 'gripper_states', 'index_in_demo', 'joint_states']>,
 <KeysViewHDF5 ['actions', 'obs']>)

In [12]:
# f.close()

In [14]:
demo_name = demos[10]
print(demo_name)
demo=f['data'][demo_name]
# demo['obs/uid'][:]

demo_18


In [15]:
demo['obs/demo_no'][:]

array([18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18., 18

In [16]:
demo['obs/index_in_demo'][:]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [17]:
f.close()